# Copyright (c) 2020, 2021, 2022 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT

name: 'get-cmake'
description: 'Installs CMake and Ninja, and caches them on cloud based GitHub cache, and/or on the local GitHub runner cache.'
author: 'Luca Cappa https://github.com/lukka'
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  cmakeVersion:
    required: false
    description: "Optional CMake version, expressed with the semantic version syntax, e.g. '~3.25.0' for the most recent 3.25.x, `Ë†3.25.0` for the most recent 3.x version, or a specific version `3.25.2'. Or `latest` or `latestrc` for the latest stable or release candidate version. If not specified the `latest` is installed."
  ninjaVersion:
    required: false
    description: "Optional Ninja version, same syntax as `cmakeVersion` input. If not specified, `latest` is installed"
  useCloudCache:
    required: false
    description: "Optional argument indicating whether to use the cloud based storage of the GitHub cache. Suited for the GitHub-hosted runners."
    default: true
  useLocalCache:
    required: false
    description: "Optional argument indicating whether to use the local cache on the GitHub runner file system. Suited for the self-hosted GitHub runners."
    default: false

branding:
  icon: 'terminal'  
  color: 'green'
