name: 'build-test'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  generate_catalog_build_and_test:
    uses: ./.github/workflows/build-test-tmpl.yml
    with:
      runs-on: "['macos-latest']"
      generate-catalog: true
    secrets:
      token:
        ${{ secrets.SSH_PRIVATE_KEY }}

  build_and_test:
    needs: generate_catalog_build_and_test
    uses: ./.github/workflows/build-test-tmpl.yml
    with:
      runs-on: "['windows-latest', 'ubuntu-latest']"
      generate-catalog: false
    secrets:
      token:
        ${{ github.token }}

  build_and_test_arm:
    needs: generate_catalog_build_and_test
    if: false #Disable buildjet's arm based runners usage.
    uses: ./.github/workflows/build-test-tmpl.yml
    with:
      runs-on: "['buildjet-2vcpu-ubuntu-2204-arm']"
      generate-catalog: false
    secrets:
      token:
        ${{ github.token }}

  test_user_provided_version:
    needs: build_and_test
    uses: ./.github/workflows/functional-tests-tmpl.yml
    with:
      runs-on: "['ubuntu-latest', 'macos-latest', 'windows-latest']"
      versions: "[\"{'cmake':'','ninja':''}\",\
        \"{cmake:'3.22.6', 'ninja':'1.11.1'}\",\
        \"{'cmake':'3.25.0-rc4','ninja':'latest'}\",\
        \"{'cmake':'latest','ninja':'~1.10.0'}\",\
        \"{'cmake':'latestrc','ninja':'^1.11.0'}\",\
        \"{'cmake':'~3.25.0','ninja':''}\",\
        \"{'cmake':'^3.1.1','ninja':''}\",\
        \"{'cmake':'~3.0.0','ninja':''}\"]"
    secrets:
      token:
        ${{ github.token }}

  test_user_provided_version_arm:
    needs: build_and_test_arm
    uses: ./.github/workflows/functional-tests-tmpl.yml
    if: false #Disable buildjet's arm based runners usage.
    with:
      runs-on: "['buildjet-2vcpu-ubuntu-2204-arm']"
      experimental: true
      versions: "[\"{'cmake':'','ninja':''}\",\
        \"{cmake:'3.22.6', 'ninja':'1.11.1'}\",\
        \"{'cmake':'3.25.0-rc4','ninja':'latest'}\",\
        \"{'cmake':'latest','ninja':'~1.10.0'}\",\
        \"{'cmake':'latestrc','ninja':'^1.11.0'}\",\
        \"{'cmake':'~3.25.0','ninja':''}\",\
        \"{'cmake':'^3.1.1','ninja':''}\"]"
    secrets:
      token:
        ${{ github.token }}
