name: 'build-test'

on: [pull_request, push]

jobs:
  build_and_test:
    name: '${{ matrix.os }}: build and test'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        npm install
        npm run test
      name: build and test
    - uses: ./
      name: validation test by running get-cmake
    - run: |
        which cmake
        cmake --version
        CMAKE_VER="$(cmake --version)"
        if ! [[ "$CMAKE_VER" =~ .*"3.18.0".* ]]; then
          echo "ASSERTION FAILED! Instead of 3.18.0, found: "
          echo "$CMAKE_VER"
          exit -1
        fi
      shell: bash
