name: 'build-test'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * FRI'
  workflow_dispatch:

jobs:
  generate_catalog_build_and_test:
    uses: ./.github/workflows/build-test-tmpl.yml
    with:
      runs-on: "['ubuntu-latest']"
      generate-catalog: true
    secrets:
      token:
        ${{ github.token }}

  build_and_test:
    needs: generate_catalog_build_and_test
    uses: ./.github/workflows/build-test-tmpl.yml
    with:
      runs-on: "['windows-latest', 'macos-latest']"
      generate-catalog: false
    secrets:
      token:
        ${{ github.token }}

  build_and_test_arm:
    needs: generate_catalog_build_and_test
    uses: ./.github/workflows/build-test-tmpl.yml
    with:
      runs-on: "['buildjet-2vcpu-ubuntu-2204-arm']"
      generate-catalog: false
    secrets:
      token:
        ${{ github.token }}

  test_user_provided_version:
    needs: build_and_test
    uses: ./.github/workflows/functional-tests-tmpl.yml
    with:
      runs-on: "['ubuntu-latest', 'macos-latest', 'windows-latest']"
    secrets:
      token:
        ${{ github.token }}

  test_user_provided_version_arm:
    needs: build_and_test_arm
    uses: ./.github/workflows/functional-tests-tmpl.yml
    with:
      runs-on: "['buildjet-2vcpu-ubuntu-2204-arm']"
      experimental: true
    secrets:
      token:
        ${{ github.token }}
