name: 'build-test'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

env:
  CMAKE_LATEST: 3.24.2
  NINJA_LATEST: 1.11.1

jobs:
  build_and_test:
    name: '${{ matrix.os }}: build and test'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: |
        npm install
        npm run test
      name: build and test
    - uses: ./
      name: validation test by running get-cmake
    - name: CMake version check
      run: |
        which cmake
        cmake --version
        CMAKE_VER="$(cmake --version)"
        if ! [[ "$CMAKE_VER" =~ .*"${CMAKE_LATEST}".* ]]; then
          echo "ASSERTION FAILED! Instead of ${CMAKE_LATEST}, found: "
          echo "$CMAKE_VER"
          exit -1
        fi
      shell: bash
    - name: ninja version check
      run: |
        which ninja
        ninja --version
        NINJA_VER="$(ninja --version)"
        if ! [[ "$NINJA_VER" =~ .*"${NINJA_LATEST}".* ]]; then
          echo "ASSERTION FAILED! Instead of ${NINJA_LATEST}, found: "
          echo "$NINJA_VER"
          exit -1
        fi
      shell: bash

  # TODO templatize the tests iterating on the versions.
  test_user_provided_version:
    name: '${{ matrix.os }}: functional test (${{ matrix.cmake }}, ${{ matrix.ninja }})'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cmake: ["", "3.22.6"]
        ninja: ["", "1.11.0"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - uses: ./
      name: validation test by running get-cmake
      with:
        cmakeVersion: ${{ matrix.cmake }}
        ninjaVersion: ${{ matrix.ninja }}
    - name: CMake version check ${{ matrix.cmake }}
      run: |
        which cmake
        cmake --version
        CMAKE_VER="$(cmake --version)"
        EXPECTED_CMAKE_VER="${{ matrix.cmake }}"
        [ -z "${EXPECTED_CMAKE_VER}" ] && EXPECTED_CMAKE_VER="${{ env.CMAKE_LATEST}}"
        if ! [[ "$CMAKE_VER" =~ .*"${EXPECTED_CMAKE_VER}".* ]]; then
          echo "ASSERTION FAILED! Instead of ${EXPECTED_CMAKE_VER}, found: "
          echo "$CMAKE_VER"
          exit -1
        fi
      shell: bash
    - name: ninja version check ${{ matrix.ninja }}
      run: |
        which ninja
        ninja --version
        NINJA_VER="$(ninja --version)"
        EXPECTED_NINJA_VER="${{ matrix.ninja }}"
        [ -z "$EXPECTED_NINJA_VER" ] && EXPECTED_NINJA_VER="${{ env.NINJA_LATEST}}"
        if ! [[ "$NINJA_VER" =~ .*"${{ matrix.ninja }}".* ]]; then
          echo "ASSERTION FAILED! Instead of $EXPECTED_NINJA_VER, found: "
          echo "$NINJA_VER"
          exit -1
        fi
      shell: bash

